FROM nvidia/cuda:12.3.1-devel-ubuntu22.04

WORKDIR /model

RUN apt update -y && apt install python3 -y && apt install python3-pip -y

COPY requirements.txt requirements.txt

RUN CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install -r requirements.txt

COPY start.sh start.sh

CMD [ "bash", "start.sh" ]
